### ISSUE TITLE
Error: Error building `Cbc`

### ISSUE THREAD

**Issue by orhanabar** [JuliaOpt/Cbc.jl#74] opened 2018-10-16 16:05 UTC
I am trying to build Cbc on Windows 10 and I am getting the error below. I am using Julia 1.0.1
I install the same version on Mac OSX and it is working without an issue. 
I also installed vcredist_x86.exe and vc_redist.x64.exe as suggested. But the error still remains.

 Error: Error building `Cbc`:
│
│ ERROR: The system cannot find the file specified.
│ C:\Users\<user>\.julia\packages\WinRPM\Y9QdZ\cache\2\mingw64-libstdc%2B%2B6-8.2.0-2.1.noarch.cpio
│
│
│
│ System ERROR:
│ The system cannot find the file specified.
│ [ Info: Updating WinRPM package list
│ [ Info: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
│ [ Info: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
│ ┌ Info: Packages to install:
│ └   join(names(todo), ", ") = "libstdc++6, Cbc"
│ ┌ Info: Downloading:
│ └   name = "libstdc++6"
│ ┌ Info: Extracting:
│ └   name = "libstdc++6"
│ ERROR: LoadError: MethodError: no method matching pipeline_error(::Int64)
│ Closest candidates are:
│   pipeline_error(!Matched::Base.ProcessChain) at process.jl:711
│   pipeline_error(!Matched::Base.Process) at process.jl:704
│ Stacktrace:
│  [1] macro expansion at .\logging.jl:309 [inlined] (repeats 2 times)
│  [2] do_install(::WinRPM.Package) at C:\Users\<user>\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:465
│  [3] do_install at C:\Users\<user>\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:456 [inlined]
│  [4] macro expansion at .\logging.jl:320 [inlined]
│  [5] #install#19(::Bool, ::Function, ::WinRPM.Package) at C:\Users\<user>\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:385
│  [6] #install at .\none:0 [inlined]
│  [7] #install#17 at C:\Users\<user>\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:372 [inlined]
│  [8] #install at .\none:0 [inlined] (repeats 2 times)
│  [9] (::getfield(WinRPM, Symbol("##34#35")){WinRPM.RPM})() at C:\Users\<user>\.julia\packages\WinRPM\Y9QdZ\src\winrpm_bindeps.jl:42
│  [10] run(::getfield(WinRPM, Symbol("##34#35")){WinRPM.RPM}) at C:\Users\<user>\.julia\packages\BinDeps\ZEval\src\BinDeps.jl:478
│  [11] macro expansion at .\logging.jl:308 [inlined]
│  [12] run(::BinDeps.SynchronousStepCollection) at C:\Users\<user>\.julia\packages\BinDeps\ZEval\src\BinDeps.jl:518
│  [13] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\<user>\.julia\packages\BinDeps\ZEval\src\dependencies.jl:944
│  [14] satisfy!(::BinDeps.LibraryDependency) at C:\Users\<user>\.julia\packages\BinDeps\ZEval\src\dependencies.jl:922
│  [15] top-level scope at C:\Users\<user>\.julia\packages\BinDeps\ZEval\src\dependencies.jl:977
│  [16] include at .\boot.jl:317 [inlined]
│  [17] include_relative(::Module, ::String) at .\loading.jl:1041
│  [18] include(::Module, ::String) at .\sysimg.jl:29
│  [19] include(::String) at .\client.jl:388
│  [20] top-level scope at none:0
│ in expression starting at C:\Users\<user>\.julia\packages\Cbc\s0xmI\deps\build.jl:64
│
│ 7-Zip [64] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
│
│ Scanning the drive for archives:
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1069

**Comment by mlubin** [comment] 2018-10-16 16:45
This is a duplicate of https://github.com/JuliaOpt/Cbc.jl/issues/56

**Closed by mlubin** 2018-10-16 16:45 UTC
