### ISSUE TITLE
Upgrade Cbc version

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaOpt/Cbc.jl#117] opened 2019-07-01 19:57 UTC
Please upgrade the Cbc version to 2.10.3 (or later) so that Cbc.jl can take advantage of the upstream fixes for #94 and #99.

**Comment by GunnarFarneback** [comment] 2019-08-13 17:06
What is the procedure to perform an upstream upgrade? Is there some way I can assist? Would a PR to CbcBuilder that bumps some version numbers be at all helpful?

cc: @juan-pablo-vielma

**Comment by mlubin** [comment] 2019-08-13 19:52
@juan-pablo-vielma, could you document how to update the BinaryBuilder binaries? This will be a recurring question.

**Comment by GunnarFarneback** [comment] 2019-09-03 05:55
Bump.

**Comment by juan-pablo-vielma** [comment] 2019-09-05 19:40
@GunnarFarneback I added 2.10.3, but it's failing the tests. Any thoughts on why it's failing are welcome. You can try it with `] add https://github.com/juan-pablo-vielma/Cbc.jl.git#jpv/bb-v2.10.3`

@mlubin For COIN the upgrade procedure is currently a mess and somewhat of an "art" 🙂 To get it to compile I had to update several of the dependencies and ARM builds with gcc 4 still didn't work. We should re-think the process. Given that we are no longer compiling on travis and the static-linking with hidden symbols approach it may be better for the binary builder for each solver to be self contained (i.e. it compiles all its dependencies). Then a PR to the builder would be more feasible.

**Comment by GunnarFarneback** [comment] 2019-09-17 16:47
I've reduced one of the failures to
```
using Cbc
using Cbc.CbcCInterface
model = CbcModel()
setObjSense(model, -1)
loadProblem(model, zeros(Float64, 0, 1), [-Inf], [1.5], [2.0], Float64[], Float64[])
solve(model)
println(getBestPossibleObjValue(model))
```
where the last call returns -1.7976931348623157e308 instead of the expected 3.0.

**Comment by juan-pablo-vielma** [comment] 2019-10-02 14:37
Yes, looks like the problem is on `getBestPossibleObjValue`. 

With v2.10.3, running the following continuous model:
```julia
model = Model(with_optimizer(Cbc.Optimizer, logLevel=3))
@variable(model, x)
@objective(model, Max, -2.0*x + 1)
@constraint(model, x >= 1.5 )
optimize!(model)
println(objective_bound(model))
println(objective_value(model))
```
yields
```
Presolve 0 (-1) rows, 0 (-1) columns and 0 (-1) elements
Optimal - objective value -3
After Postsolve, objective -3, infeasibilities - dual 0 (0), primal 0 (0)
Optimal objective -3 - 0 iterations time 0.002, Presolve 0.00
Best Obj = -1.7976931348623157e308
Obj = -2.0
```
However, running the following version with a dummy integer variable 
```julia
model = Model(with_optimizer(Cbc.Optimizer, logLevel=3))
@variable(model, x)
@variable(model, z >=0, Int)
@objective(model, Max, -2.0*x + 1)
@constraint(model, x >= 1.5 + z)
optimize!(model)
println(objective_bound(model))
println(objective_value(model))
```
yields 
```
Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Sep  5 2019 

command line - Cbc_C_Interface -logLevel 3 -solve -quit (default strategy 1)
logLevel was changed from 1 to 3
Continuous objective value is -3 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 3 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                -3.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Best Obj = -2.0
Obj = -2.0
```
I believe that `-1.7976931348623157e308` is equal to `COIN_DBL_MAX`, so the output seems to suggest that, in v2.10.3, Cbc is not even called when there are no integer variables. I am looking at the Cbc code now to try to figure out, but it may be something in Osi too, so any suggestions on where to look are welcome. 

As a reference, with v2.9.9 the continuous model yields 
```
Welcome to the CBC MILP Solver 
Version: 2.9.9 
Build Date: Dec 31 2018 

command line - Cbc_C_Interface -logLevel 3 -solve -quit (default strategy 1)
logLevel was changed from 1 to 3
Presolve 0 (-1) rows, 0 (-1) columns and 0 (-1) elements
Empty problem - 0 rows, 0 columns and 0 elements
Optimal - objective value -3
After Postsolve, objective -3, infeasibilities - dual 0 (0), primal 0 (0)
Optimal objective -3 - 0 iterations time 0.002, Presolve 0.00
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00
Best Obj = -2.0
Obj = -2.0
```
and the one with a dummy integer yields
```
Welcome to the CBC MILP Solver 
Version: 2.9.9 
Build Date: Dec 31 2018 

command line - Cbc_C_Interface -logLevel 3 -solve -quit (default strategy 1)
logLevel was changed from 1 to 3
Continuous objective value is -3 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 3 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                -3.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Best Obj = -2.0
Obj = -2.0
```

**Comment by juan-pablo-vielma** [comment] 2019-10-05 18:23
Ok, I updated the version you can add through `] add https://github.com/juan-pablo-vielma/Cbc.jl.git#jpv/bb-v2.10.3` and it seems to be working. 

Besides the bestBound issue (coin-or/Cbc#267) there is a problem with statuses in v2.10.3 that may be better to fix in Cbc#master so it may take some time. In the mean time, I made a simple patch that seems to make it work. The patch just removes an optimization in Cbc's C-interface that calls an LP solver instead of Cbc when there are no integer variables, so its cost is probably marginal. 

@GunnarFarneback could you please check if it is working. 

PS There also seems to be an issue with MOI v0.9.3, so #jpv/bb-v2.10.3 also has some temporary restrictions to avoid this.

**Comment by GunnarFarneback** [comment] 2019-10-06 21:04
Yes, this works fine with the #94 and #99 problems.

**Comment by juan-pablo-vielma** [comment] 2019-10-09 19:58
Ok, I created a self-contained binary_builder.jl that should be easier to update. 

@GunnarFarneback could you please double check `https://github.com/juan-pablo-vielma/Cbc.jl.git#jpv/bb-v2.10.3 ` one last time, just in case. 

@mlubin could you please check the update instructions in https://github.com/JuliaOpt/CbcBuilder/blob/master/build_tarballs.jl

Once #126 gets merged (need this for tests to pass with MOI v0.9.5) I will create a PR for https://github.com/juan-pablo-vielma/Cbc.jl.git#jpv/bb-v2.10.3

**Comment by GunnarFarneback** [comment] 2019-10-09 20:53
Yes, still looks good.

**Comment by mlubin** [comment] 2019-10-11 14:27
Minor comments on `build_tarballs.jl`:

https://github.com/JuliaOpt/CbcBuilder/blob/800a31dfa10d5ad1872770851fe3ce607ef3c981/build_tarballs.jl#L7-L9

"Modify the build script" could be "Modify the build script (e.g., changing START-EASY-CHANGE-BLOCK)"

https://github.com/JuliaOpt/CbcBuilder/blob/800a31dfa10d5ad1872770851fe3ce607ef3c981/build_tarballs.jl#L16

"[ test Cbc" should be "] test Cbc"

https://github.com/JuliaOpt/CbcBuilder/blob/800a31dfa10d5ad1872770851fe3ce607ef3c981/build_tarballs.jl#L21-L22

I didn't really understand the comment about different extensions. Could you add an example?

**Comment by juan-pablo-vielma** [comment] 2019-10-13 20:30
I refined the update instructions in `build_tarballs.jl` and added PR #127 to upgrade Cbc to v2.10.3

**Comment by agcmoser** [comment] 2019-10-28 07:15
For what it's worth: I recently tested the latest Cbc.jl package on ARM (RaspberryPi 4) and for some MILP problems Cbc just totally crashed my Julia application. I built Cbc from source myself (2.10.3) and added set the JULIA_CBC_LIBRARY_PATH and rebuild Cbc.jl --> No sudden crashes anymore. The pre-compiled binarys for ARMv7 seems to have some problems. Output from uname -a is "Linux raspberrypi 4.19.80-v7l+"

**Comment by juan-pablo-vielma** [comment] 2019-10-29 18:28
@agcmoser did the previous version run ok? Can you send me the output during the failure of the current version?

**Comment by agcmoser** [comment] 2019-10-30 09:20
@juan-pablo-vielma : this is the error output: 


[ Info: Optimizing   time step: t[k] := 2018-01-24T14:15:00
--
┌ Warning:   MathOptInterface.VariablePrimalStart() is not supported by   MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{Cbc.Optimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}.   This
│     information will be discarded. = "information will be   discarded."
└ @ MathOptInterface.Utilities   ~/.julia/packages/MathOptInterface/XE04a/src/Utilities/copy.jl:140
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Oct  7 2019
 
command line - Cbc_C_Interface -logLevel   1 -ratioGap 0.01 -solve -quit (default strategy 1)
ratioGap was changed from 0 to 0.01
Continuous objective value is 3.71373 -   0.05 seconds
Cgl0004I processed model has 554 rows,   553 columns (288 integer (288 of which binary)) and 1584 elements
Cbc0012I Integer solution of 3.7554052   found by DiveCoefficient after 0 iterations and 0 nodes (0.13 seconds)
Cbc0038I Full problem 554 rows 553   columns, reduced to 459 rows 268 columns - 29 fixed gives 193, 192 - ok now
Cbc0031I 16 added rows had average   density of 21.3125
Cbc0013I At root node, 109 cuts changed   objective from 3.7137293 to 3.7554052 in 3 passes
Cbc0014I Cut generator 0 (Probing) - 44   row cuts average 2.6 elements, 0 column cuts (0 active)  in 0.012 seconds - new frequency is 1
Cbc0014I Cut generator 1 (Gomory) - 7   row cuts average 51.6 elements, 0 column cuts (0 active)  in 0.007 seconds - new frequency is -100
Cbc0014I Cut generator 2 (Knapsack) - 0   row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.003 seconds - new frequency is -100
Cbc0014I Cut generator 3 (Clique) - 0   row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.000 seconds - new frequency is -100
Cbc0014I Cut generator 4   (MixedIntegerRounding2) - 20 row cuts average 16.3 elements, 0 column cuts (0   active)  in 0.002 seconds - new   frequency is -100
Cbc0014I Cut generator 5 (FlowCover) - 0   row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.003 seconds - new frequency is -100
Cbc0014I Cut generator 6 (TwoMirCuts) -   277 row cuts average 62.3 elements, 0 column cuts (0 active)  in 0.058 seconds - new frequency is -100
Cbc0001I Search completed - best   objective 3.755405173129091, took 62 iterations and 0 nodes (0.26 seconds)
Cbc0035I Maximum depth 0, 176 variables   fixed on reduced cost
Cuts at root node changed objective from   3.71373 to 3.75541
Probing was tried 3 times and created 44   cuts of which 0 were active after adding rounds of cuts (0.012 seconds)
Gomory was tried 3 times and created 7   cuts of which 0 were active after adding rounds of cuts (0.007 seconds)
Knapsack was tried 3 times and created 0   cuts of which 0 were active after adding rounds of cuts (0.003 seconds)
Clique was tried 3 times and created 0   cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 3 times   and created 20 cuts of which 0 were active after adding rounds of cuts (0.002   seconds)
FlowCover was tried 3 times and created   0 cuts of which 0 were active after adding rounds of cuts (0.003 seconds)
TwoMirCuts was tried 3 times and created   277 cuts of which 0 were active after adding rounds of cuts (0.058 seconds)
ZeroHalf was tried 1 times and created 0   cuts of which 0 were active after adding rounds of cuts (0.004 seconds)
julia:   ../../../../Osi/src/Osi/OsiPresolve.cpp:513: virtual void   OsiPresolve::postsolve(bool): Zusicherung »status !=   CoinWarmStartBasis::atLowerBound \|\| originalModel_->getColLower()[i] >   -originalModel_->getInfinity()« nicht erfüllt.
 
signal (6): Abgebrochen
in expression starting at   /home/pi/Downloads/dev_ems_julia/ems_DeterministicEmsController_building_test.jl:381
gsignal at   /lib/arm-linux-gnueabihf/libc.so.6 (unknown line)
Allocations: 1151186215 (Pool:   1150771279; Big: 414936); GC: 7528
Abgebrochen

**Closed** 2020-04-22 21:20 UTC
