### ISSUE TITLE
Build Error on Windows

### ISSUE THREAD

**Issue by QuantumBits** [JuliaOpt/Cbc.jl#72] opened 2018-10-05 19:50 UTC
After installing Cbc.jl for the first time on Julia 1.0.1 on a Windows 7 machine, I found the following error message:

![image](https://user-images.githubusercontent.com/6290682/46556847-c62b9b00-c89c-11e8-92c6-b3a219e01444.png)

I was **actually** able to fix it by going to the folder specified and renaming the following file:

> mingw64-libstdc++6-8.2.0-2.1.noarch.cpio

to the following:

> mingw64-libstdc%2B%2B6-8.2.0-2.1.noarch.cpio

(basically replaced '+' characters with "%2B").

**Comment by mlubin** [comment] 2018-10-09 02:28
This is a duplicate of https://github.com/JuliaOpt/Cbc.jl/issues/56.

**Closed by mlubin** 2018-10-09 02:28 UTC
