### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by ChrisNabold** [JuliaOpt/Cbc.jl#84] opened 2018-12-11 08:11 UTC
If I add Cbc for installation I receive the following errors
[CbcInstallError.txt](https://github.com/JuliaOpt/Cbc.jl/files/2666573/CbcInstallError.txt)

**Comment by blegat** [comment] 2018-12-11 08:33
Duplicate of https://github.com/JuliaOpt/Cbc.jl/issues/56

**Closed by blegat** 2018-12-11 08:33 UTC
